apiVersion: v1
kind: Service
metadata: 
  name: kong-monitoring
  namespace: kong-dp
  labels: 
    app: kong-monitoring
spec:
  selector: 
    app.kubernetes.io/instance: kong-dp
  type: ClusterIP
  ports:
  - name: metrics
    protocol: TCP
    port: 8100
    targetPort: 8100